#公用配置
server:
  tomcat:
    uri-encoding: UTF-8
#  context-path: /admin

micro-service:
  name: zyk-sso-server

spring:
  boot:
    admin:
        client:
          prefer-ip: true
          metadata:
            user.name: zyk          #These two are needed so that the server
            user.password: 123456   #can access the proteceted client endpoints
        url: http://192.168.43.217:8084/
        username: zyk
        password: 123456
  profiles:
    active: dev
  mvc:
    view:
      prefix: /WEB-INF/view
      suffix: .jsp

management:
  security:
    enabled: false # spring-boot 1.5.2之后严格执行安全策略，所以需要配置这个为false

info: #定义各种额外的详情给服务端显示
  app:
    name: zyk-sso-server
    version: v1.0.1

logging:
  config: classpath:logback-spring.xml

mybatis:
  config-location: /mybatis/mybatis-config.xml
  mapper-locations: /mybatis/mapper/*Mapper.xml,/mybatis/ReuseSQL.xml

---
spring:
  profiles: dev

server:
  port: 8086


---
spring:
  profiles: test

server:
  port: 8086


---
spring:
  profiles: pro

server:
  port: 8086



